# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='Someone forgot to save or submit there work', max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='image', max_length=500)),
                ('file', models.FileField(upload_to='article/static/article/img/uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title Missing', max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.Author')),
            ],
        ),
        migrations.AddField(
            model_name='articlefiles',
            name='linkedArticle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleInfo'),
        ),
        migrations.AddField(
            model_name='articlecontent',
            name='linkedArticle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleInfo'),
        ),
    ]
